language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - .travis/load-vendor.sh

script:
  - composer update
  - mkdir -p builds/logs
  - php vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration .travis/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls
